spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/arturo_crud
    username: zeva
    password: zeva16
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

